// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMuv5KbW7uy37eI2viAqXY3NPAgjc1Kzc',
    appId: '1:998118069720:web:a3e29b6799450538488ead',
    messagingSenderId: '998118069720',
    projectId: 'bootcampmaterial-c4f37',
    authDomain: 'bootcampmaterial-c4f37.firebaseapp.com',
    storageBucket: 'bootcampmaterial-c4f37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsV1XuJbtKbjoSqPpKol8B_Evck0PdI5o',
    appId: '1:998118069720:android:03073dc62266b51a488ead',
    messagingSenderId: '998118069720',
    projectId: 'bootcampmaterial-c4f37',
    storageBucket: 'bootcampmaterial-c4f37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXzzCbBVUKfAQVliS0SRbVpt83WABWlOQ',
    appId: '1:998118069720:ios:dbe2dd52e533826a488ead',
    messagingSenderId: '998118069720',
    projectId: 'bootcampmaterial-c4f37',
    storageBucket: 'bootcampmaterial-c4f37.appspot.com',
    iosClientId: '998118069720-dubpobqlmcoq4qb4prgksdq1gu2vcbce.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXzzCbBVUKfAQVliS0SRbVpt83WABWlOQ',
    appId: '1:998118069720:ios:dbe2dd52e533826a488ead',
    messagingSenderId: '998118069720',
    projectId: 'bootcampmaterial-c4f37',
    storageBucket: 'bootcampmaterial-c4f37.appspot.com',
    iosClientId: '998118069720-dubpobqlmcoq4qb4prgksdq1gu2vcbce.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
